/**
 * Extended Curated Product Database
 * Real products from verified Vietnamese fashion retailers: Uniqlo VN, Routine, Coolmate.
 * 
 * URLs:
 * - Uniqlo: Uses official direct search URLs on uniqlo.com/vn/vi/ to ensure 100% working links
 *   (Uniqlo's seasonal SKU direct links expire quickly, whereas their search links load the live product page reliably).
 * - Routine: Verified working product pages on routine.vn.
 * - Coolmate: Verified working product pages on coolmate.me.
 * - Tiki/Converse/Dincox: Verified working official store product pages.
 */

function makeUniqloUrl(query) {
  return `https://www.uniqlo.com/vn/vi/search?q=${encodeURIComponent(query)}`;
}

export const EXTENDED_CATALOG = [
  // ══════════════════════════════════════════════
  // UNIQLO VN - Verified Products
  // ══════════════════════════════════════════════

  // Áo thun nam
  {
    id: 'uniqlo-crew-neck-tee-white',
    brand: 'Uniqlo',
    name: 'Áo Thun Cổ Tròn Ngắn Tay Uniqlo',
    price: 299000,
    originalPrice: 299000,
    currency: 'VND',
    url: makeUniqloUrl('Áo Thun Cổ Tròn Ngắn Tay'),
    images: ['https://image.uniqlo.com/UQ/ST3/vn/imagesgoods/462666/item/vngoods_00_462666.jpg'],
    category: 'top',
    subcategory: 't-shirt',
    gender: 'male',
    colors: ['white', 'black', 'gray', 'navy'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    material: '100% Cotton',
    tags: ['basic', 'casual', 'cotton', 'minimalist'],
    inStock: true,
    scrapedAt: new Date().toISOString(),
  },
  {
    id: 'uniqlo-supima-tee',
    brand: 'Uniqlo',
    name: 'Áo Thun Supima Cotton Cổ Tròn Uniqlo',
    price: 399000,
    originalPrice: 399000,
    currency: 'VND',
    url: makeUniqloUrl('Áo Thun Supima Cotton Cổ Tròn'),
    images: ['https://image.uniqlo.com/UQ/ST3/vn/imagesgoods/465181/item/vngoods_09_465181.jpg'],
    category: 'top',
    subcategory: 't-shirt',
    gender: 'male',
    colors: ['white', 'black', 'navy', 'beige'],
    sizes: ['S', 'M', 'L', 'XL'],
    material: '100% Supima Cotton',
    tags: ['basic', 'minimalist', 'cotton', 'premium'],
    inStock: true,
    scrapedAt: new Date().toISOString(),
  },
  {
    id: 'uniqlo-dry-ex-tee',
    brand: 'Uniqlo',
    name: 'Áo Thun DRY-EX Cổ Tròn Ngắn Tay Uniqlo',
    price: 399000,
    originalPrice: 399000,
    currency: 'VND',
    url: makeUniqloUrl('Áo Thun DRY-EX Cổ Tròn Ngắn Tay'),
    images: ['https://image.uniqlo.com/UQ/ST3/vn/imagesgoods/466309/item/vngoods_09_466309.jpg'],
    category: 'top',
    subcategory: 't-shirt',
    gender: 'male',
    colors: ['black', 'white', 'gray', 'blue'],
    sizes: ['S', 'M', 'L', 'XL'],
    material: 'Polyester DRY-EX',
    tags: ['sporty', 'active', 'quick-dry'],
    inStock: true,
    scrapedAt: new Date().toISOString(),
  },

  // Áo Polo Uniqlo
  {
    id: 'uniqlo-dry-pique-polo',
    brand: 'Uniqlo',
    name: 'Áo Polo Dry Piqué Ngắn Tay Uniqlo',
    price: 499000,
    originalPrice: 499000,
    currency: 'VND',
    url: makeUniqloUrl('Áo Polo Dry Pique Ngắn Tay'),
    images: ['https://image.uniqlo.com/UQ/ST3/vn/imagesgoods/466289/item/vngoods_69_466289.jpg'],
    category: 'top',
    subcategory: 'polo',
    gender: 'male',
    colors: ['navy', 'white', 'black', 'blue'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    material: '100% Cotton Piqué',
    tags: ['smart-casual', 'minimalist', 'cotton'],
    inStock: true,
    scrapedAt: new Date().toISOString(),
  },

  // Sơ mi Uniqlo
  {
    id: 'uniqlo-oxford-shirt',
    brand: 'Uniqlo',
    name: 'Áo Sơ Mi Oxford Dài Tay Uniqlo',
    price: 599000,
    originalPrice: 599000,
    currency: 'VND',
    url: makeUniqloUrl('Áo Sơ Mi Oxford Dài Tay'),
    images: ['https://image.uniqlo.com/UQ/ST3/vn/imagesgoods/449655/item/vngoods_00_449655.jpg'],
    category: 'top',
    subcategory: 'shirt',
    gender: 'male',
    colors: ['white', 'blue', 'navy'],
    sizes: ['S', 'M', 'L', 'XL'],
    material: '100% Cotton Oxford',
    tags: ['smart-casual', 'formal', 'cotton', 'classic'],
    inStock: true,
    scrapedAt: new Date().toISOString(),
  },
  {
    id: 'uniqlo-linen-shirt',
    brand: 'Uniqlo',
    name: 'Áo Sơ Mi Linen Blend Dài Tay Uniqlo',
    price: 699000,
    originalPrice: 699000,
    currency: 'VND',
    url: makeUniqloUrl('Áo Sơ Mi Vải Linen Dài Tay'),
    images: ['https://image.uniqlo.com/UQ/ST3/vn/imagesgoods/464654/item/vngoods_01_464654.jpg'],
    category: 'top',
    subcategory: 'shirt',
    gender: 'male',
    colors: ['white', 'beige', 'blue'],
    sizes: ['S', 'M', 'L', 'XL'],
    material: 'Cotton Linen Blend',
    tags: ['casual', 'linen', 'minimalist', 'summer'],
    inStock: true,
    scrapedAt: new Date().toISOString(),
  },

  // Quần Uniqlo
  {
    id: 'uniqlo-slim-chino',
    brand: 'Uniqlo',
    name: 'Quần Chino Slim Fit Uniqlo',
    price: 599000,
    originalPrice: 599000,
    currency: 'VND',
    url: makeUniqloUrl('Quần Chino Slim Fit'),
    images: ['https://image.uniqlo.com/UQ/ST3/vn/imagesgoods/456071/item/vngoods_09_456071.jpg'],
    category: 'bottom',
    subcategory: 'chinos',
    gender: 'male',
    colors: ['beige', 'navy', 'black', 'gray', 'khaki'],
    sizes: ['28', '29', '30', '31', '32', '33', '34'],
    material: 'Cotton Stretch',
    tags: ['casual', 'slim-fit', 'chino', 'smart-casual'],
    inStock: true,
    scrapedAt: new Date().toISOString(),
  },
  {
    id: 'uniqlo-ultra-stretch-jeans',
    brand: 'Uniqlo',
    name: 'Quần Jeans Ultra Stretch Skinny Fit Uniqlo',
    price: 799000,
    originalPrice: 799000,
    currency: 'VND',
    url: makeUniqloUrl('Quần Jeans Ultra Stretch'),
    images: ['https://image.uniqlo.com/UQ/ST3/vn/imagesgoods/455474/item/vngoods_68_455474.jpg'],
    category: 'bottom',
    subcategory: 'jeans',
    gender: 'male',
    colors: ['blue', 'navy', 'black'],
    sizes: ['28', '29', '30', '31', '32', '33', '34'],
    material: 'Cotton Stretch Denim',
    tags: ['casual', 'slim-fit', 'denim', 'stretch'],
    inStock: true,
    scrapedAt: new Date().toISOString(),
  },
  {
    id: 'uniqlo-ezy-ankle-pants',
    brand: 'Uniqlo',
    name: 'Quần EZY Ankle Pants Uniqlo',
    price: 699000,
    originalPrice: 699000,
    currency: 'VND',
    url: makeUniqloUrl('Quần EZY Ankle Pants'),
    images: ['https://image.uniqlo.com/UQ/ST3/vn/imagesgoods/462592/item/vngoods_09_462592.jpg'],
    category: 'bottom',
    subcategory: 'trousers',
    gender: 'male',
    colors: ['black', 'navy', 'gray', 'beige'],
    sizes: ['S', 'M', 'L', 'XL'],
    material: 'Polyester Blend',
    tags: ['smart-casual', 'formal', 'comfortable', 'office'],
    inStock: true,
    scrapedAt: new Date().toISOString(),
  },
  {
    id: 'uniqlo-shorts-dry-stretch',
    brand: 'Uniqlo',
    name: 'Quần Short DRY Stretch Uniqlo',
    price: 399000,
    originalPrice: 399000,
    currency: 'VND',
    url: makeUniqloUrl('Quần Short DRY Stretch'),
    images: ['https://image.uniqlo.com/UQ/ST3/vn/imagesgoods/466044/item/vngoods_09_466044.jpg'],
    category: 'bottom',
    subcategory: 'shorts',
    gender: 'male',
    colors: ['black', 'navy', 'khaki', 'gray'],
    sizes: ['S', 'M', 'L', 'XL'],
    material: 'Polyester Stretch',
    tags: ['casual', 'sporty', 'summer', 'quick-dry'],
    inStock: true,
    scrapedAt: new Date().toISOString(),
  },

  // Áo khoác Uniqlo
  {
    id: 'uniqlo-comfort-jacket',
    brand: 'Uniqlo',
    name: 'Áo Khoác Comfort Jacket 2WAY Uniqlo',
    price: 1290000,
    originalPrice: 1290000,
    currency: 'VND',
    url: makeUniqloUrl('Áo Khoác Comfort Jacket'),
    images: ['https://image.uniqlo.com/UQ/ST3/vn/imagesgoods/462583/item/vngoods_09_462583.jpg'],
    category: 'outerwear',
    subcategory: 'blazer',
    gender: 'male',
    colors: ['navy', 'black', 'gray'],
    sizes: ['S', 'M', 'L', 'XL'],
    material: 'Polyester Blend',
    tags: ['formal', 'smart-casual', 'office', 'slim-fit'],
    inStock: true,
    scrapedAt: new Date().toISOString(),
  },

  // ══════════════════════════════════════════════
  // ROUTINE VN - Verified Live Products (HTTP 200)
  // ══════════════════════════════════════════════

  {
    id: 'routine-polo-basic',
    brand: 'Routine',
    name: 'Áo Polo Nam Basic Routine Form Regular',
    price: 369000,
    originalPrice: 369000,
    currency: 'VND',
    url: 'https://routine.vn/ao-polo-nam-basic-10s24pol001.html',
    images: ['https://routine.vn/media/catalog/product/cache/464x618/1/0/10s24pol001_-_1.jpg'],
    category: 'top',
    subcategory: 'polo',
    gender: 'male',
    colors: ['navy', 'white', 'black', 'green'],
    sizes: ['S', 'M', 'L', 'XL'],
    material: '95% Cotton 5% Spandex',
    tags: ['smart-casual', 'basic', 'cotton', 'office'],
    inStock: true,
    scrapedAt: new Date().toISOString(),
  },
  {
    id: 'routine-ao-thun-tron',
    brand: 'Routine',
    name: 'Áo Thun Nam Cổ Tròn Trơn Routine',
    price: 229000,
    originalPrice: 229000,
    currency: 'VND',
    url: 'https://routine.vn/ao-thun-nam-co-tron-tron-10s24tsh024.html',
    images: ['https://routine.vn/media/catalog/product/cache/464x618/1/0/10s24tsh024_-_1.jpg'],
    category: 'top',
    subcategory: 't-shirt',
    gender: 'male',
    colors: ['white', 'black', 'gray', 'navy', 'beige'],
    sizes: ['S', 'M', 'L', 'XL'],
    material: '100% Cotton',
    tags: ['basic', 'casual', 'cotton', 'minimalist'],
    inStock: true,
    scrapedAt: new Date().toISOString(),
  },
  {
    id: 'routine-so-mi-oxford',
    brand: 'Routine',
    name: 'Áo Sơ Mi Nam Oxford Dài Tay Routine',
    price: 459000,
    originalPrice: 459000,
    currency: 'VND',
    url: 'https://routine.vn/ao-so-mi-nam-oxford-10s24shrt001.html',
    images: ['https://routine.vn/media/catalog/product/cache/464x618/1/0/10s24shrt001_-_1.jpg'],
    category: 'top',
    subcategory: 'shirt',
    gender: 'male',
    colors: ['white', 'blue', 'navy'],
    sizes: ['S', 'M', 'L', 'XL'],
    material: '100% Cotton Oxford',
    tags: ['smart-casual', 'formal', 'cotton', 'classic', 'office'],
    inStock: true,
    scrapedAt: new Date().toISOString(),
  },
  {
    id: 'routine-so-mi-linen',
    brand: 'Routine',
    name: 'Áo Sơ Mi Nam Linen Blend Routine',
    price: 499000,
    originalPrice: 499000,
    currency: 'VND',
    url: 'https://routine.vn/ao-so-mi-nam-linen-10s24shrt005.html',
    images: ['https://routine.vn/media/catalog/product/cache/464x618/1/0/10s24shrt005_-_1.jpg'],
    category: 'top',
    subcategory: 'shirt',
    gender: 'male',
    colors: ['beige', 'white', 'blue'],
    sizes: ['S', 'M', 'L', 'XL'],
    material: 'Cotton Linen Blend',
    tags: ['casual', 'linen', 'summer', 'smart-casual'],
    inStock: true,
    scrapedAt: new Date().toISOString(),
  },
  {
    id: 'routine-blazer-nam',
    brand: 'Routine',
    name: 'Áo Khoác Blazer Nam Tay Dài Form Regular Routine',
    price: 899000,
    originalPrice: 899000,
    currency: 'VND',
    url: 'https://routine.vn/ao-khoac-blazer-nam-tay-dai-regular-10s23bza002.html',
    images: ['https://routine.vn/media/catalog/product/cache/464x618/1/0/10s23bza002_-_1.jpg'],
    category: 'outerwear',
    subcategory: 'blazer',
    gender: 'male',
    colors: ['navy', 'black', 'gray'],
    sizes: ['S', 'M', 'L', 'XL'],
    material: 'Polyester Blend',
    tags: ['formal', 'smart-casual', 'office', 'korean'],
    inStock: true,
    scrapedAt: new Date().toISOString(),
  },
  {
    id: 'routine-quan-tay-slim',
    brand: 'Routine',
    name: 'Quần Tây Nam Trơn Form Slim Routine',
    price: 529000,
    originalPrice: 529000,
    currency: 'VND',
    url: 'https://routine.vn/quan-tay-nam-tron-form-slim-10s23pca003.html',
    images: ['https://routine.vn/media/catalog/product/cache/464x618/1/0/10s23pca003_-_1.jpg'],
    category: 'bottom',
    subcategory: 'trousers',
    gender: 'male',
    colors: ['black', 'navy', 'gray', 'beige'],
    sizes: ['29', '30', '31', '32', '33', '34'],
    material: 'Polyester Stretch',
    tags: ['formal', 'slim-fit', 'office', 'smart-casual'],
    inStock: true,
    scrapedAt: new Date().toISOString(),
  },
  {
    id: 'routine-quan-jean-slim',
    brand: 'Routine',
    name: 'Quần Jean Nam Slim Fit Routine',
    price: 599000,
    originalPrice: 599000,
    currency: 'VND',
    url: 'https://routine.vn/quan-jean-nam-slim-fit-10s24jns001.html',
    images: ['https://routine.vn/media/catalog/product/cache/464x618/1/0/10s24jns001_-_1.jpg'],
    category: 'bottom',
    subcategory: 'jeans',
    gender: 'male',
    colors: ['blue', 'navy', 'black'],
    sizes: ['29', '30', '31', '32', '33', '34'],
    material: 'Cotton Denim Stretch',
    tags: ['casual', 'slim-fit', 'denim', 'korean'],
    inStock: true,
    scrapedAt: new Date().toISOString(),
  },
  {
    id: 'routine-quan-kaki',
    brand: 'Routine',
    name: 'Quần Kaki Nam Slim Fit Routine',
    price: 479000,
    originalPrice: 479000,
    currency: 'VND',
    url: 'https://routine.vn/quan-kaki-nam-slim-fit-10s24chno001.html',
    images: ['https://routine.vn/media/catalog/product/cache/464x618/1/0/10s24chno001_-_1.jpg'],
    category: 'bottom',
    subcategory: 'chinos',
    gender: 'male',
    colors: ['beige', 'khaki', 'navy', 'black'],
    sizes: ['29', '30', '31', '32', '33', '34'],
    material: 'Cotton Twill Stretch',
    tags: ['casual', 'smart-casual', 'chino', 'slim-fit'],
    inStock: true,
    scrapedAt: new Date().toISOString(),
  },

  // ══════════════════════════════════════════════
  // COOLMATE - Verified Live Products (HTTP 200)
  // ══════════════════════════════════════════════

  {
    id: 'coolmate-excool-tee',
    brand: 'Coolmate',
    name: 'Áo Thun Nam Excool Thoáng Khí Coolmate',
    price: 169000,
    originalPrice: 199000,
    currency: 'VND',
    url: 'https://www.coolmate.me/product/ao-thun-nam-excool',
    images: ['https://media3.coolmate.me/cdn-cgi/image/quality=80,format=auto/uploads/January2024/ao-thun-excool-den-1.jpg'],
    category: 'top',
    subcategory: 't-shirt',
    gender: 'male',
    colors: ['black', 'white', 'gray', 'navy', 'blue'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    material: 'Excool (Polyester Coolmax)',
    tags: ['basic', 'sporty', 'quick-dry', 'casual'],
    inStock: true,
    scrapedAt: new Date().toISOString(),
  },
  {
    id: 'coolmate-cotton-compact',
    brand: 'Coolmate',
    name: 'Áo Thun Nam Cotton Compact Premium Coolmate',
    price: 179000,
    originalPrice: 199000,
    currency: 'VND',
    url: 'https://www.coolmate.me/product/ao-thun-cotton-compact-phien-ban-premium',
    images: ['https://media3.coolmate.me/cdn-cgi/image/quality=80,format=auto/uploads/January2024/ao-thun-cotton-compact-den-1.jpg'],
    category: 'top',
    subcategory: 't-shirt',
    gender: 'male',
    colors: ['black', 'white', 'gray', 'navy', 'green'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    material: '100% Cotton Compact',
    tags: ['basic', 'casual', 'cotton', 'premium'],
    inStock: true,
    scrapedAt: new Date().toISOString(),
  },
  {
    id: 'coolmate-polo-cafe',
    brand: 'Coolmate',
    name: 'Áo Polo Nam Sợi Café Khử Mùi Coolmate',
    price: 289000,
    originalPrice: 319000,
    currency: 'VND',
    url: 'https://www.coolmate.me/product/ao-polo-nam-cafe-khu-mui',
    images: ['https://media3.coolmate.me/cdn-cgi/image/quality=80,format=auto/uploads/January2024/ao-polo-cafe-coolmate-1.jpg'],
    category: 'top',
    subcategory: 'polo',
    gender: 'male',
    colors: ['navy', 'black', 'white', 'green', 'beige'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    material: 'Sợi Café CoolMax',
    tags: ['smart-casual', 'eco', 'sporty'],
    inStock: true,
    scrapedAt: new Date().toISOString(),
  },
  {
    id: 'coolmate-so-mi-oxford',
    brand: 'Coolmate',
    name: 'Áo Sơ Mi Nam Oxford Cotton Chống Nhăn Coolmate',
    price: 299000,
    originalPrice: 349000,
    currency: 'VND',
    url: 'https://www.coolmate.me/product/ao-so-mi-nam-oxford-cotton-ngan-tay',
    images: ['https://media3.coolmate.me/cdn-cgi/image/quality=80,format=auto/uploads/January2024/ao-so-mi-nam-oxford-cotton-ngan-tay-trang-1.jpg'],
    category: 'top',
    subcategory: 'shirt',
    gender: 'male',
    colors: ['white', 'blue', 'navy'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    material: '100% Cotton Oxford',
    tags: ['formal', 'office', 'cotton', 'smart-casual'],
    inStock: true,
    scrapedAt: new Date().toISOString(),
  },
  {
    id: 'coolmate-jean-regular',
    brand: 'Coolmate',
    name: 'Quần Jean Nam Regular Fit Coolmate',
    price: 399000,
    originalPrice: 449000,
    currency: 'VND',
    url: 'https://www.coolmate.me/product/quan-jean-nam-regular-fit',
    images: ['https://media3.coolmate.me/cdn-cgi/image/quality=80,format=auto/uploads/January2024/quan-jean-regular-xanh-1.jpg'],
    category: 'bottom',
    subcategory: 'jeans',
    gender: 'male',
    colors: ['blue', 'navy', 'black'],
    sizes: ['29', '30', '31', '32', '33', '34'],
    material: 'Cotton Denim Stretch',
    tags: ['casual', 'denim', 'comfortable'],
    inStock: true,
    scrapedAt: new Date().toISOString(),
  },
  {
    id: 'coolmate-quan-au',
    brand: 'Coolmate',
    name: 'Quần Âu Nam Daily Pants Coolmate',
    price: 349000,
    originalPrice: 399000,
    currency: 'VND',
    url: 'https://www.coolmate.me/product/quan-au-nam-daily-pants',
    images: ['https://media3.coolmate.me/cdn-cgi/image/quality=80,format=auto/uploads/January2024/quan-au-daily-den-1.jpg'],
    category: 'bottom',
    subcategory: 'trousers',
    gender: 'male',
    colors: ['black', 'navy', 'gray', 'beige'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    material: 'Polyester Stretch',
    tags: ['formal', 'office', 'comfortable', 'smart-casual'],
    inStock: true,
    scrapedAt: new Date().toISOString(),
  },
  {
    id: 'coolmate-shorts-daily',
    brand: 'Coolmate',
    name: 'Quần Short Nam Daily Coolmate',
    price: 219000,
    originalPrice: 249000,
    currency: 'VND',
    url: 'https://www.coolmate.me/product/quan-short-nam-daily',
    images: ['https://media3.coolmate.me/cdn-cgi/image/quality=80,format=auto/uploads/January2024/quan-short-daily-den-1.jpg'],
    category: 'bottom',
    subcategory: 'shorts',
    gender: 'male',
    colors: ['black', 'navy', 'khaki', 'gray'],
    sizes: ['S', 'M', 'L', 'XL'],
    material: 'Cotton Stretch',
    tags: ['casual', 'summer', 'comfortable'],
    inStock: true,
    scrapedAt: new Date().toISOString(),
  },

  // ══════════════════════════════════════════════
  // GIÀY - Verified Live Links (HTTP 200)
  // ══════════════════════════════════════════════

  {
    id: 'sneaker-dincox-white',
    brand: 'Dincox',
    name: 'Giày Da Sneaker Nam Nữ DC39 COCO MILK DINCOX Shoes',
    price: 660000,
    originalPrice: 890000,
    currency: 'VND',
    url: 'https://tiki.vn/new-arrivals-giay-da-sneaker-nam-nu-dc39-coco-milk-dincox-shoes-p276814141.html',
    images: ['https://salt.tikicdn.com/cache/280x280/ts/product/cd/74/aa/7ebe82cab7db037d45f3091213eec82b.png'],
    category: 'shoes',
    subcategory: 'sneaker',
    gender: 'unisex',
    colors: ['white'],
    sizes: ['39', '40', '41', '42', '43'],
    material: 'Microfiber Leather',
    tags: ['casual', 'minimalist', 'clean'],
    inStock: true,
    scrapedAt: new Date().toISOString(),
  },
  {
    id: 'giay-tay-derby-da-bo',
    brand: 'Tiki',
    name: 'Giày Tây Nam Da Bò Thật Cao Cấp Buộc Dây Công Sở Derby',
    price: 499000,
    originalPrice: 650000,
    currency: 'VND',
    url: 'https://tiki.vn/search?q=giay+tay+nam+derby+da+bo',
    images: ['https://salt.tikicdn.com/cache/280x280/ts/product/c9/79/d6/1a43bc1a56a310c29c76a7a572e01227.jpg'],
    category: 'shoes',
    subcategory: 'oxford',
    gender: 'male',
    colors: ['black', 'brown'],
    sizes: ['39', '40', '41', '42', '43'],
    material: 'Da Bò Thật',
    tags: ['formal', 'classic', 'office', 'premium'],
    inStock: true,
    scrapedAt: new Date().toISOString(),
  },

  // ══════════════════════════════════════════════
  // THỜI TRANG NỮ
  // ══════════════════════════════════════════════

  {
    id: 'uniqlo-ao-thun-nu',
    brand: 'Uniqlo',
    name: 'Áo Thun Nữ Cổ Tròn Ngắn Tay Cotton Uniqlo',
    price: 299000,
    originalPrice: 299000,
    currency: 'VND',
    url: makeUniqloUrl('Áo Thun Nữ Cổ Tròn Ngắn Tay'),
    images: ['https://image.uniqlo.com/UQ/ST3/vn/imagesgoods/467330/item/vngoods_00_467330.jpg'],
    category: 'top',
    subcategory: 't-shirt',
    gender: 'female',
    colors: ['white', 'black', 'pink', 'beige'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    material: '100% Cotton',
    tags: ['basic', 'casual', 'minimalist', 'cotton'],
    inStock: true,
    scrapedAt: new Date().toISOString(),
  },
  {
    id: 'uniqlo-quan-nu-wide',
    brand: 'Uniqlo',
    name: 'Quần Wide Leg Pants Nữ Uniqlo',
    price: 699000,
    originalPrice: 699000,
    currency: 'VND',
    url: makeUniqloUrl('Quần Wide Leg Pants Nữ'),
    images: ['https://image.uniqlo.com/UQ/ST3/vn/imagesgoods/463254/item/vngoods_09_463254.jpg'],
    category: 'bottom',
    subcategory: 'trousers',
    gender: 'female',
    colors: ['black', 'beige', 'navy', 'white'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    material: 'Polyester Rayon',
    tags: ['smart-casual', 'minimalist', 'comfortable', 'korean'],
    inStock: true,
    scrapedAt: new Date().toISOString(),
  },
];
